# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
 
      
#- task: UiPathRunJob@2
#  inputs:
#    orchestratorConnection: 'Uipath_Testing'
#    processName: 'Azure_Demo'
#    folderName: 'Modren Example'
#    user: 'uipath\balamanikanta.krishn'
#- task: UiPathPack@2
#  inputs:
#    versionType: 'CurrentVersion'
#    projectJsonPath: '$(Build.SourcesDirectory)\project.json'
#    outputType: 'Process'
#    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
#    orchestratorConnection: 'Uipath_Testing'

#- task: UiPathTest@2
#  inputs:
#    testTarget: 'TestProject'
#    orchestratorConnection: 'Uipath_Testing'
#    folderName: 'Test'
#- task: UiPathDeploy@2
#  inputs:
#    orchestratorConnection: 'Uipath_Testing'
#    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
#    folderName: 'Test'
#    entryPoints: 'Main.xaml'
#- task: UiPathPack@2
#  inputs:
#    versionType: 'CurrentVersion'
#    projectJsonPath: '$(Build.ArtifactStagingDirectory)\project.json'
#    orchestratorConnection: 'Uipath_Testing'
#    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: UiPathPack@2
  inputs:
    versionType: 'ManualVersion'
    version: '$(Build_name)'
    projectJsonPath: '$(Build.SourcesDirectory)'
    outputType: 'Process'
    orchestratorConnection: 'Uipath_Testing'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'